path_estilo : "/Users/luis/Documents/Maestria/correccion/Simulacion-calzado/data/datos_m.csv"
path_suela :  "./data/suela_gen.csv"
path_plantilla :  "./data/plantilla_gen.csv"
path_modelos : "modelos/ppo_indice_4"
path_logs : "logs"
nombre_modelo : "ppo_4"