path_estilo : "./data/Libro1.csv"
path_suela :  "./data/suela_gen copy.csv"
path_plantilla :  "./data/plantilla_gen copy.csv"
path_modelos : "modelos/ppo_indice_4"
path_logs : "logs"
nombre_modelo : "ppo_4"